#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "apify-teste"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[deco]
workspace = "deco-team"
enable_workflows = false
local = false
bindings = []

[deco.integration]
description = "Automate web scraping and data extraction using Apify actors. List, run, and monitor actors, retrieve results, and manage runs with support for sync and async execution."
icon = "https://apify.com/favicon.ico"
friendlyName = "Apify-teste"