#:schema node_modules/@decocms/runtime/config-schema.json
name = "openrouter"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[deco]
workspace = "deco"
enable_workflows = false
local = false

[[kv_namespaces]]
binding = "STREAM_SESSIONS"
id = "cabb6fbb32f5411889f737a050b54ee2"
