#:schema node_modules/@decocms/runtime/config-schema.json
name = "reddit"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[deco]
workspace = "deco"
enable_workflows = false
local = false

[deco.integration]
description = "Browse Reddit subreddits and search for posts about any topic."
icon = "https://www.redditstatic.com/desktop2x/img/favicon/android-icon-192x192.png"
friendlyName = "Reddit"
